### ISSUE TITLE
implement Facade Design pattern in golang

### ISSUE THREAD

**Issue by nilesh05apr** [nilesh05apr/DesignPatternExamples#1]
Implement a method/app based on Facade Design Pattern using Golang.
refer: https://en.wikipedia.org/wiki/Facade_pattern 
for demo UML diagram and C++ implementation.

**Comment by Dhi13man** [comment]
Taking this up

**Comment by Dhi13man** [comment]
@nilesh05apr Please check PR #6. Should close this issue.

**Comment by nilesh05apr** [comment]
@Dhi13man thank you so much for your time and interest. can you please add documentation along with the code.

**Comment by Dhi13man** [comment]
Added. Please check

**Comment by Dhi13man** [comment]
Could you add `hacktoberfest-accepted` tag/label to this PR please? Doesn't count for hacktoberfest otherwise
